#!/usr/bin/bash

# flags
help_flag=false
recursion_flag=false
lowercase_flag=false
uppercase_flag=false

# parameters handling with getopts
while getopts :rluh params
do
    case $params in  # set flags according to parameters
    h)  help_flag=true ;;
    r)  recursion_flag=true ;;
    l)  lowercase_flag=true ;;
    u)  uppercase_flag=true ;;
    ?)  echo Unknown argument. 1>&2
        help_flag=true ;;
    esac
done

shift $(($OPTIND - 1))  # shift positional arguments when all defined arguments are parsed

# display help and terminate execution when help flag is raised or parameters are invalid
if $help_flag || ($uppercase_flag && $lowercase_flag) || ( [ $OPTIND -eq 1 ] && [ -z "$2" ]); then

    cat << EOT
Usage: modify [OPTION] [SED PATTERN] [[DIR]FILEs]
Modify name of the FILEs.

Options:
 -r     rename FILEs recursively
 -l     change all uppercase letters into lowercase letters
 -u     change all lowercase letters into uppercase letters
 -h     display this help

Alternatively, a SED PATTERN may be used instead of uppercase and lowercase options.
EOT

    exit # terminate the script
else
    sed_pattern=$1  # if sed pattern will be used it will be taken from this variable
    IFS=$'\n'   # set the delimiter as new line character to avoid wrong filenames in variables

    for item in "$@"
    do 
        if $recursion_flag; then # rename files in recursive way
            for file_with_path in $(find "$item" -type f)
                do
                    file_name=$(basename "$file_with_path")
                    dir_name=$(dirname "$file_with_path")
                    
                    if $lowercase_flag; then
                        mv -- "$file_with_path" "$dir_name/${file_name,,}" 1>&/dev/null # change all upercase letters in the name into uppercase

                    elif $uppercase_flag; then 
                        mv -- "$file_with_path" "$dir_name/${file_name^^}" 1>&/dev/null # change all upercase letters in the name into uppercase

                    elif [ $sed_pattern != "$item" ]; then
                        mv -- "$file_with_path" "$dir_name/$(echo "$file_name" | sed "$1")" 1>&/dev/null   # change the name according to sed pattern
                    fi
                done

        elif [ -f $item ]; then # check if the item is a file; non-recursive variant
            file_name=$(basename $item)
            dir_name=$(dirname $item)
            
            if $lowercase_flag; then
                mv "$item" "$dir_name/${file_name,,}" 1>&/dev/null # change all upercase letters in the name into lowercase

            elif $uppercase_flag; then
                mv "$item" "$dir_name/${file_name^^}" 1>&/dev/null # change all upercase letters in the name into lowercas

            elif [ $sed_pattern != "$item" ]; then                         
                mv "$item" "$dir_name/$(echo "$file_name" | sed "$1")" 1>&/dev/null  # change the name according to sed pattern
            fi
        fi
    done
fi