#!/usr/bin/bash

# flags
help_flag=false
recursion_flag=false
lowercase_flag=false
uppercase_flag=false

# parameters handling with getopts
while getopts :rluh param
do
    case $param in  # set flags according to parameters
    h)  help_flag=true ;;
    r)  recursion_flag=true ;;
    l)  lowercase_flag=true ;;
    u)  uppercase_flag=true ;;
    ?)  echo Unknown argument.
        help_flag=true ;;
    esac
done

shift $(($OPTIND - 1))  # shift positional arguments when all defined arguments are parsed

if $help_flag; then # display help and terminate execution
    echo -e "Usage: modify [OPTION]... [SED PATTERN] [[DIR]FILE]"
    echo -e "Modify name of the FILEs.\n"
    echo -e "Options:"
    echo -e " -r\t rename FILEs recursively"
    echo -e " -l\t change all uppercase letters into lowercase letters"
    echo -e " -u\t change all lowercase letters into uppercase letters"
    echo -e " -h\t display this help\n"
    echo -e "Alternatively, a SED PATTERN may be used instead of uppercase and lowercase options."
    exit

elif $lowercase_flag; then
    mv $1 ${1,,}   # change all upercase letters in the name into lowercase

elif $uppercase_flag; then
    mv $1 ${1^^}   # change all upercase letters in the name into lowercase

else                                      
    mv $2 $(echo $2 | sed $1)   # change the name according to sed pattern
fi